AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestructura para Agente de IA MCP - Amazon Connect Educación Superior'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Ambiente de despliegue
  
  ConnectInstanceArn:
    Type: String
    Default: 'arn:aws:connect:us-east-1:520754296204:instance/983955e0-57a9-4633-aad0-f87f18072f04'
    Description: ARN de la instancia de Amazon Connect

Resources:
  # DynamoDB Table para Perfiles Unificados
  StudentProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-student-profiles'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: studentId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: studentId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: EducacionConnectIA

  # S3 Bucket para Base de Conocimiento
  KnowledgeBaseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Environment}-educacion-knowledge-base-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: EducacionConnectIA

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-educacion-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt StudentProfilesTable.Arn
                  - !Sub '${StudentProfilesTable.Arn}/index/*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt KnowledgeBaseBucket.Arn
                  - !Sub '${KnowledgeBaseBucket.Arn}/*'
        - PolicyName: CloudWatchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudwatch:PutMetricData
                Resource: '*'
        - PolicyName: ConnectAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - connect:StartOutboundVoiceContact
                  - connect:StopContact
                Resource: !Ref ConnectInstanceArn

  # Lambda Function - Main Agent Handler
  AgentHandlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-educacion-agent-handler'
      Runtime: nodejs18.x
      Handler: dist/index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DYNAMODB_TABLE: !Ref StudentProfilesTable
          S3_BUCKET: !Ref KnowledgeBaseBucket
          CONNECT_INSTANCE_ARN: !Ref ConnectInstanceArn
          LOG_LEVEL: INFO
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: EducacionConnectIA

  # Lambda Function - Academic Record API
  AcademicRecordFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-academic-record-api'
      Runtime: nodejs18.x
      Handler: dist/lambdas/academic-record.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DYNAMODB_TABLE: !Ref StudentProfilesTable
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: EducacionConnectIA

  # Lambda Function - Certificate Generation
  CertificateGenerationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-certificate-generation'
      Runtime: nodejs18.x
      Handler: dist/lambdas/certificate-generation.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DYNAMODB_TABLE: !Ref StudentProfilesTable
          S3_BUCKET: !Ref KnowledgeBaseBucket
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: EducacionConnectIA

  # CloudWatch Log Groups
  AgentHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AgentHandlerFunction}'
      RetentionInDays: 30

  AcademicRecordLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AcademicRecordFunction}'
      RetentionInDays: 30

  CertificateGenerationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${CertificateGenerationFunction}'
      RetentionInDays: 30

  # CloudWatch Alarms
  AgentHandlerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-agent-handler-errors'
      AlarmDescription: 'Alerta cuando hay errores en el handler principal'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AgentHandlerFunction

  AgentHandlerLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-agent-handler-latency'
      AlarmDescription: 'Alerta cuando la latencia es alta'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 25000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AgentHandlerFunction

Outputs:
  StudentProfilesTableName:
    Description: 'Nombre de la tabla DynamoDB de perfiles'
    Value: !Ref StudentProfilesTable
    Export:
      Name: !Sub '${Environment}-StudentProfilesTable'

  KnowledgeBaseBucketName:
    Description: 'Nombre del bucket S3 para base de conocimiento'
    Value: !Ref KnowledgeBaseBucket
    Export:
      Name: !Sub '${Environment}-KnowledgeBaseBucket'

  AgentHandlerFunctionArn:
    Description: 'ARN de la función Lambda principal'
    Value: !GetAtt AgentHandlerFunction.Arn
    Export:
      Name: !Sub '${Environment}-AgentHandlerFunctionArn'

  AcademicRecordFunctionArn:
    Description: 'ARN de la función Lambda de registros académicos'
    Value: !GetAtt AcademicRecordFunction.Arn
    Export:
      Name: !Sub '${Environment}-AcademicRecordFunctionArn'

  CertificateGenerationFunctionArn:
    Description: 'ARN de la función Lambda de generación de certificados'
    Value: !GetAtt CertificateGenerationFunction.Arn
    Export:
      Name: !Sub '${Environment}-CertificateGenerationFunctionArn'
